### ISSUE TITLE
Error: Database `system` does not exist on the database server at `localhost:5432`.

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/Nestjs-Docker-Issues#1]
Error: Database `system` does not exist on the database server at `localhost:5432`.

**Comment by ikmz0104** [comment]
localhost:5432 で動作している PostgreSQL サーバー上に "system" という名前のデータベースが存在しない

**Comment by ikmz0104** [comment]
https://zenn.dev/monicle/articles/6961f6cd666d5b
```yml: docker-compose.yml

version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres:14
    container_name: sample-nestjs
    volumes:
      - db-data:/var/lib/postgresql/sample-nestjs/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
```

これでdocker-compose upすると、
```
sample-nestjs  | server stopped
sample-nestjs  | 
sample-nestjs  | PostgreSQL init process complete; ready for start up.
sample-nestjs  | 
sample-nestjs  | 2023-06-26 06:54:32.578 UTC [1] LOG:  starting PostgreSQL 14.8 (Debian 14.8-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
sample-nestjs  | 2023-06-26 06:54:32.578 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
sample-nestjs  | 2023-06-26 06:54:32.578 UTC [1] LOG:  listening on IPv6 address "::", port 5432
sample-nestjs  | 2023-06-26 06:54:32.580 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
sample-nestjs  | 2023-06-26 06:54:32.583 UTC [61] LOG:  database system was shut down at 2023-06-26 06:54:32 UTC
sample-nestjs  | 2023-06-26 06:54:32.587 UTC [1] LOG:  database system is ready to accept connections
```
